package `fun`.abbas.wps_adb.model

enum class EasyActionCategory {
    SYSTEM,
    DISPLAY,
    APP_CONTROL,
    DEVELOPER,
    DEVICE_HARDWARE,
    SYSTEM_SOFTWARE,
    STORAGE_MEMORY,
    ACTIVITY_WINDOW,
    PERFORMANCE,
}

enum class EasyActionKind {
    REBOOT,
    RECOVERY_MODE,
    CLEAR_APP_CACHE,
    TAKE_SCREENSHOT,
    TAKE_SCREENSHOT_TO_CLIPBOARD,
    SCREEN_RECORD,
    FORCE_STOP_APP,
    CLEAR_APP_DATA,
    TOGGLE_SHOW_REFRESH_RATE,
    TOGGLE_POINTER_LOCATION,
    TOGGLE_SHOW_SURFACE_UPDATES,
    TOGGLE_SHOW_VIEW_UPDATES,
    TOGGLE_GPU_OVERDRAW,
    TOGGLE_STRICT_MODE,
    TOGGLE_GPU_PROFILE_BARS,
    TOGGLE_DONT_KEEP_ACTIVITIES,
    TOGGLE_SHOW_LAYOUT_BOUNDS,
    INFO_DEVICE_MODEL,
    INFO_DEVICE_BRAND,
    INFO_DEVICE_MANUFACTURER,
    INFO_HARDWARE_PLATFORM,
    INFO_CPU_ABI,
    INFO_SCREEN_SIZE,
    INFO_SCREEN_DENSITY,
    INFO_BATTERY_LEVEL,
    INFO_BATTERY_STATUS,
    INFO_ANDROID_VERSION,
    INFO_SDK_VERSION,
    INFO_SECURITY_PATCH,
    INFO_BUILD_ID,
    INFO_KERNEL_VERSION,
    INFO_DATA_STORAGE,
    INFO_TOTAL_MEMORY,
    INFO_AVAILABLE_MEMORY,
    INFO_CURRENT_FOCUS,
    INFO_ACTIVITY_TOP,
    INFO_RESUMED_ACTIVITY,
    INFO_RESUMED_ACTIVITY_PACKAGE,
    DUMP_LAYOUT_TO_CLIPBOARD,
    INFO_MEMINFO_ALL,
    INFO_MEMINFO_PACKAGE,
    INFO_CPUINFO,
    INFO_PROCSTATS,
}

data class EasyActionDefinition(
    val kind: EasyActionKind,
    val category: EasyActionCategory,
    val requiresPackage: Boolean = false,
    val destructive: Boolean = false,
    val isToggle: Boolean = false,
)

val DefaultEasyActions: List<EasyActionDefinition> = listOf(
    EasyActionDefinition(EasyActionKind.REBOOT, EasyActionCategory.SYSTEM, destructive = true),
    EasyActionDefinition(EasyActionKind.RECOVERY_MODE, EasyActionCategory.SYSTEM, destructive = true),
    EasyActionDefinition(EasyActionKind.TAKE_SCREENSHOT, EasyActionCategory.DISPLAY),
    EasyActionDefinition(EasyActionKind.TAKE_SCREENSHOT_TO_CLIPBOARD, EasyActionCategory.DISPLAY),
    EasyActionDefinition(EasyActionKind.SCREEN_RECORD, EasyActionCategory.DISPLAY),
    EasyActionDefinition(EasyActionKind.CLEAR_APP_CACHE, EasyActionCategory.APP_CONTROL, requiresPackage = true),
    EasyActionDefinition(EasyActionKind.FORCE_STOP_APP, EasyActionCategory.APP_CONTROL, requiresPackage = true),
    EasyActionDefinition(EasyActionKind.CLEAR_APP_DATA, EasyActionCategory.APP_CONTROL, requiresPackage = true, destructive = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_SHOW_REFRESH_RATE, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_POINTER_LOCATION, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_SHOW_SURFACE_UPDATES, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_SHOW_VIEW_UPDATES, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_GPU_OVERDRAW, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_STRICT_MODE, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_GPU_PROFILE_BARS, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_DONT_KEEP_ACTIVITIES, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.TOGGLE_SHOW_LAYOUT_BOUNDS, EasyActionCategory.DEVELOPER, isToggle = true),
    EasyActionDefinition(EasyActionKind.INFO_DEVICE_MODEL, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_DEVICE_BRAND, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_DEVICE_MANUFACTURER, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_HARDWARE_PLATFORM, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_CPU_ABI, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_SCREEN_SIZE, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_SCREEN_DENSITY, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_BATTERY_LEVEL, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_BATTERY_STATUS, EasyActionCategory.DEVICE_HARDWARE),
    EasyActionDefinition(EasyActionKind.INFO_ANDROID_VERSION, EasyActionCategory.SYSTEM_SOFTWARE),
    EasyActionDefinition(EasyActionKind.INFO_SDK_VERSION, EasyActionCategory.SYSTEM_SOFTWARE),
    EasyActionDefinition(EasyActionKind.INFO_SECURITY_PATCH, EasyActionCategory.SYSTEM_SOFTWARE),
    EasyActionDefinition(EasyActionKind.INFO_BUILD_ID, EasyActionCategory.SYSTEM_SOFTWARE),
    EasyActionDefinition(EasyActionKind.INFO_KERNEL_VERSION, EasyActionCategory.SYSTEM_SOFTWARE),
    EasyActionDefinition(EasyActionKind.INFO_DATA_STORAGE, EasyActionCategory.STORAGE_MEMORY),
    EasyActionDefinition(EasyActionKind.INFO_TOTAL_MEMORY, EasyActionCategory.STORAGE_MEMORY),
    EasyActionDefinition(EasyActionKind.INFO_AVAILABLE_MEMORY, EasyActionCategory.STORAGE_MEMORY),
    EasyActionDefinition(EasyActionKind.INFO_CURRENT_FOCUS, EasyActionCategory.ACTIVITY_WINDOW),
    EasyActionDefinition(EasyActionKind.INFO_ACTIVITY_TOP, EasyActionCategory.ACTIVITY_WINDOW),
    EasyActionDefinition(EasyActionKind.INFO_RESUMED_ACTIVITY, EasyActionCategory.ACTIVITY_WINDOW),
    EasyActionDefinition(EasyActionKind.INFO_RESUMED_ACTIVITY_PACKAGE, EasyActionCategory.ACTIVITY_WINDOW),
    EasyActionDefinition(EasyActionKind.DUMP_LAYOUT_TO_CLIPBOARD, EasyActionCategory.ACTIVITY_WINDOW),
    EasyActionDefinition(EasyActionKind.INFO_MEMINFO_ALL, EasyActionCategory.PERFORMANCE),
    EasyActionDefinition(EasyActionKind.INFO_MEMINFO_PACKAGE, EasyActionCategory.PERFORMANCE, requiresPackage = true),
    EasyActionDefinition(EasyActionKind.INFO_CPUINFO, EasyActionCategory.PERFORMANCE),
    EasyActionDefinition(EasyActionKind.INFO_PROCSTATS, EasyActionCategory.PERFORMANCE),
)

fun EasyActionCategory.defaultExpanded(): Boolean = when (this) {
    EasyActionCategory.SYSTEM,
    EasyActionCategory.DISPLAY,
    EasyActionCategory.APP_CONTROL,
    -> true
    EasyActionCategory.DEVELOPER,
    EasyActionCategory.DEVICE_HARDWARE,
    EasyActionCategory.SYSTEM_SOFTWARE,
    EasyActionCategory.STORAGE_MEMORY,
    EasyActionCategory.ACTIVITY_WINDOW,
    EasyActionCategory.PERFORMANCE,
    -> false
}
